version: '3'

services:
  node:
    image: node:18
    depends_on:
      - redis
      - node_worker
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: node /app/src/server-http.js

  node_worker:
    build:
      context: .
      dockerfile: Dockerfile_node
    depends_on:
      - redis
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./realesrgan:/app/realesrgan
      - ./node_modules:/app/node_modules
    environment:
      - FFMPEG_PATH=/app/ffmpeg/ffmpeg
      - FFPROBE_PATH=/app/ffmpeg/ffprobe
      - REAL_ESRGAN_PATH=/app/realesrgan/realesrgan-ncnn-vulkan
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: node /app/src/server-worker.js

  redis:
    image: redis:7
    ports:
      - "6379:6379"
