version: '3'

services:
  node:
    image: node:18
    container_name: node
    depends_on:
      - redis
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./src:/app/src
      - node:/app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: node /app/src/server-http.js

  worker:
    build:
      context: .
      dockerfile: Dockerfile_node
    container_name: worker
    depends_on:
      - redis
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./realesrgan:/app/realesrgan
      - ./node_modules:/app/node_modules
    environment:
      - FFMPEG_PATH=/app/ffmpeg/ffmpeg
      - FFPROBE_PATH=/app/ffmpeg/ffprobe
      - REAL_ESRGAN_PATH=/app/realesrgan/realesrgan-ncnn-vulkan
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: node /app/src/server-worker.js
    deploy:
      resources:
        reservations:
           devices:
             - driver: nvidia
               capabilities: [gpu]

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  node:
    driver: local
